const W=1087,H=1536;
const $=id=>document.getElementById(id), poster=$('poster'),ctx=poster.getContext('2d'), pe=$('photoEditor'),pctx=pe.getContext('2d');
poster.width=W;poster.height=H;
const assets={headerPhoto:{src:'apj-default.jpg',original:'apj-default.jpg'},leftLogo:{src:'nss-logo-default.jpg',original:'nss-logo-default.jpg'},rightLogo:{src:'nss-logo-default.jpg',original:'nss-logo-default.jpg'},leaderPhoto:{src:null,original:null}};
const photoState={},positions={};const memberState={};const imgCache={};let renderToken=0;
const defaults={groupName:'APJ ABDUL KALAM',mainTitle:'APJ ABDUL KALAM',subtitle:'NSS GROUP LEADER',quote:'Dream is not what you see in sleep, Dream is something that does not let you sleep.',quoteAuthor:'APJ ABDUL KALAM',footer:'NOT ME BUT YOU'};
const base={headerPhoto:[0,0],leftLogo:[0,0],rightLogo:[0,0],quote:[0,0],quoteAuthor:[0,0],title:[0,0],subtitle:[0,0],leaderCard:[0,0],leaderPhoto:[0,0],leaderName:[0,0],leaderMobile:[0,0],leaderSemester:[0,0],leaderSubject:[0,0],groupHeader:[0,0],membersArea:[0,0],footer:[0,0]};
const pNames={headerPhoto:'Header photo',leftLogo:'Left NSS logo',rightLogo:'Right NSS logo',quote:'Quote',quoteAuthor:'Quote author',title:'Main title',subtitle:'Subtitle',leaderCard:'Leader box',leaderPhoto:'Leader photo',leaderName:'Leader name',leaderMobile:'Leader mobile',leaderSemester:'Leader semester',leaderSubject:'Leader subject',groupHeader:'Group Members header',membersArea:'Members area',footer:'Footer'};
function makePos(key){if(!positions[key])positions[key]={x:0,y:0,scale:100,rotate:0};return positions[key]}
function ensurePhoto(key){if(!photoState[key])photoState[key]={zoom:100,x:0,y:0,rotate:0,brightness:100,contrast:100,saturation:100,blur:0,opacity:100,gray:false,sepia:false,flipH:false,flipV:false,tolerance:45};return photoState[key]}
function makeMember(i){if(!memberState[i])memberState[i]={x:0,y:0,photoX:0,photoY:0,savedName:'',savedMobile:'',savedSemester:'5TH SEM',savedSubject:'GENERAL'};return memberState[i]}
function esc(v){return String(v??'').trim()} function val(id){return $(id)?.value??''}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
function loadImg(src){return new Promise(resolve=>{if(!src)return resolve(null);if(imgCache[src])return resolve(imgCache[src]);const im=new Image();im.onload=()=>{imgCache[src]=im;resolve(im)};im.onerror=()=>resolve(null);im.src=src})}
function fitFont(text,max,start,min,weight='700',family='Inter'){for(let s=start;s>=min;s--){ctx.font=`${weight} ${s}px ${family}`;if(ctx.measureText(text||'').width<=max)return s}return min}
function splitLines(text,max,size,weight='400',family='Inter'){ctx.font=`${weight} ${size}px ${family}`;const words=esc(text).split(/\s+/).filter(Boolean),out=[];let line='';for(const w of words){const t=line?line+' '+w:w;if(line&&ctx.measureText(t).width>max){out.push(line);line=w}else line=t}if(line)out.push(line);return out}
function drawText(text,x,y,maxWidth,size,weight='700',align='center',color='#173f6c',family='Inter',maxLines=6){let s=size,ls=splitLines(text,maxWidth,s,weight,family);while(ls.length>maxLines&&s>8){s--;ls=splitLines(text,maxWidth,s,weight,family)}ls=ls.slice(0,maxLines);const lh=s*1.18;ctx.fillStyle=color;ctx.textAlign=align;ctx.textBaseline='middle';ls.forEach((line,i)=>{ctx.font=`${weight} ${s}px ${family}`;ctx.fillText(line,x,y+(i-(ls.length-1)/2)*lh)});}
function roundRect(x,y,w,h,r,fill,stroke,lw=2){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=lw;ctx.stroke()}}
function rowPlan(n){return ({1:[1],2:[2],3:[3],4:[4],5:[3,2],6:[3,3],7:[4,3],8:[4,4],9:[5,4],10:[5,5]})[n]||[4]}
function memberData(i){const s=makeMember(i);return{name:s.savedName||`MEMBER ${i}`,mobile:s.savedMobile||'',semester:s.savedSemester||'5TH SEM',subject:s.savedSubject||'GENERAL'}}
function p(key){return makePos(key)}
function transformPoint(x,y,key){const z=p(key);return{x:x+z.x,y:y+z.y}}
function drawPhoto(im,x,y,w,h,key,circle=true){if(!im)return;const st=ensurePhoto(key);const s=(st.zoom||100)/100;ctx.save();ctx.globalAlpha=(st.opacity||100)/100;ctx.filter=`brightness(${st.brightness}%) contrast(${st.contrast}%) saturate(${st.saturation}%) blur(${st.blur}px)${st.gray?' grayscale(100%)':''}${st.sepia?' sepia(100%)':''}`;ctx.translate(x+w/2+(st.x||0),y+h/2+(st.y||0));ctx.rotate((st.rotate||0)*Math.PI/180);ctx.scale((st.flipH?-1:1)*s,(st.flipV?-1:1)*s);if(circle){ctx.beginPath();ctx.arc(0,0,Math.min(w,h)/2,0,Math.PI*2);ctx.clip()}ctx.drawImage(im,-w/2,-h/2,w,h);ctx.restore();ctx.filter='none'}
function fillPhotoPlaceholder(x,y,w,h,label,circle=true){ctx.fillStyle='#dce8f2';if(circle){ctx.beginPath();ctx.arc(x+w/2,y+h/2,Math.min(w,h)/2,0,Math.PI*2);ctx.fill()}else{roundRect(x,y,w,h,12,'#dce8f2',null,0)};ctx.font='700 11px Inter';ctx.fillStyle='#668096';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(label,x+w/2,y+h/2)}
function initMembers(){const n=+$('memberCount').value,box=$('memberFields');box.innerHTML='';for(let i=1;i<=n;i++){const m=makeMember(i),d=document.createElement('div');d.className='member-mini';d.innerHTML=`<div class="member-mini-head"><b>Member ${i}</b><span class="pill soft">edit</span></div><label>Name<input data-mf="name" data-i="${i}" value="${m.savedName||`MEMBER ${i}`}" /></label><div class="grid2"><label>Mobile<input data-mf="mobile" data-i="${i}" value="${m.savedMobile||''}" /></label><label>Semester<input data-mf="semester" data-i="${i}" value="${m.savedSemester||'5TH SEM'}" /></label></div><label>Subject<input data-mf="subject" data-i="${i}" value="${m.savedSubject||'GENERAL'}" /></label><label>Photo<input type="file" accept="image/*" data-member-photo="${i}"></label><div class="row-actions"><button onclick="selectElement('memberCard${i}')">Box</button><button onclick="selectElement('memberPhoto${i}')">Photo</button><button onclick="selectElement('memberName${i}')">Name</button><button onclick="selectElement('memberDetails${i}')">Details</button></div>`;box.appendChild(d)}box.querySelectorAll('[data-mf]').forEach(el=>el.addEventListener('input',()=>{const m=makeMember(+el.dataset.i);m['saved'+el.dataset.mf.charAt(0).toUpperCase()+el.dataset.mf.slice(1)]=el.value;status('Updated');render()}));box.querySelectorAll('[data-member-photo]').forEach(el=>el.addEventListener('change',e=>readFile(e,'member'+e.target.dataset.memberPhoto)));populatePhotoSelect();populateElements();render()}
function populateElements(){const s=$('elementSelect'),keep=s.value;s.innerHTML='';const opts=[...Object.entries(pNames)];const n=+$('memberCount').value;for(const [k,name] of opts){const o=document.createElement('option');o.value=k;o.textContent=name;s.appendChild(o)}for(let i=1;i<=n;i++)['Card','Photo','Name','Details'].forEach(part=>{const o=document.createElement('option');o.value=`member${part==='Card'?'Card':part}${i}`;o.textContent=`Member ${i} ${part.toLowerCase()}`;s.appendChild(o)});s.value=[...s.options].some(o=>o.value===keep)?keep:'groupHeader';$('selectionLabel').textContent=labelFor(s.value);populateMemberObject(keep)}
function populateMemberObject(keep){const s=$('memberObjectSelect');s.innerHTML='';const n=+$('memberCount').value;for(let i=1;i<=n;i++){for(const part of ['Card','Photo','Name','Details']){const o=document.createElement('option');o.value=`member${part}${i}`;o.textContent=`Member ${i} ${part}`;s.appendChild(o)}}if([...s.options].some(o=>o.value===keep))s.value=keep;s.onchange=()=>selectElement(s.value)}
function labelFor(key){return pNames[key]||key.replace(/member(Card|Photo|Name|Details)(\d+)/,(_,a,b)=>`Member ${b} ${a}`)}
function getPos(key){if(key.startsWith('member')){const m=key.match(/^member(Card|Photo|Name|Details)(\d+)$/);if(m){const i=+m[2],part=m[1],mm=makeMember(i);const q=makePos(key);q.x=q.x||0;q.y=q.y||0;q.scale=q.scale||100;q.rotate=q.rotate||0;return q}}return p(key)}
function selectElement(key){if(!key)return;const s=$('elementSelect');if([...s.options].some(o=>o.value===key))s.value=key;else{$('memberObjectSelect').value=key}syncLayoutControls()}
function syncLayoutControls(){const k=$('elementSelect').value,st=getPos(k);$('posX').value=st.x;$('posY').value=st.y;$('scale').value=st.scale;$('rotate').value=st.rotate;$('posXV').textContent=st.x;$('posYV').textContent=st.y;$('scaleV').textContent=st.scale+'%';$('rotateV').textContent=st.rotate+'°';$('selectionLabel').textContent=labelFor(k)}
function nudge(dx,dy){const st=getPos($('elementSelect').value);st.x=clamp(st.x+dx,-550,550);st.y=clamp(st.y+dy,-700,700);syncLayoutControls();render()}
function centerSelected(){const st=getPos($('elementSelect').value);st.x=0;st.y=0;syncLayoutControls();render()}
function bindGeneral(){document.querySelectorAll('#tab-content input,#tab-content textarea,#tab-content select,#tab-design input').forEach(el=>{if(el.type==='file')return;el.addEventListener('input',()=>{syncDesignOutputs();status('Editing…');render()})});['posX','posY','scale','rotate'].forEach(id=>$(id).addEventListener('input',()=>{const st=getPos($('elementSelect').value);st.x=+$('posX').value;st.y=+$('posY').value;st.scale=+$('scale').value;st.rotate=+$('rotate').value;syncLayoutControls();render()}));$('elementSelect').addEventListener('change',syncLayoutControls);$('memberCount').addEventListener('change',initMembers);}
function syncDesignOutputs(){for(const id of ['cardRadius','borderWidth','ringWidth','memberGap']){const o=$(id+'V');if(o)o.textContent=$(id).value}}
function readFile(e,key){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{assets[key]={src:r.result,original:r.result};Object.keys(photoState).forEach(()=>{});ensurePhoto(key);Object.assign(photoState[key],{zoom:100,x:0,y:0,rotate:0,brightness:100,contrast:100,saturation:100,blur:0,opacity:100,gray:false,sepia:false,flipH:false,flipV:false,tolerance:45});populatePhotoSelect();$('photoSelect').value=key;syncPhotoControls();render();status('Photo uploaded')};r.readAsDataURL(f)}
function populatePhotoSelect(){const s=$('photoSelect'),keep=s.value;s.innerHTML='';const arr=[['headerPhoto','Header photo'],['leftLogo','Left NSS logo'],['rightLogo','Right NSS logo'],['leaderPhoto','Leader photo']];const n=+$('memberCount').value;for(let i=1;i<=n;i++)arr.push(['member'+i,'Member '+i+' photo']);for(const [v,t] of arr){const o=document.createElement('option');o.value=v;o.textContent=t;s.appendChild(o)}s.value=[...s.options].some(o=>o.value===keep)?keep:arr[0][0]}
function syncPhotoOutputs(st){const pairs=[['photoZoom','photoZoomV',v=>v+'%'],['photoRotate','photoRotateV',v=>v+'°'],['photoX','photoXV',v=>v],['photoY','photoYV',v=>v],['photoBrightness','photoBrightnessV',v=>v],['photoContrast','photoContrastV',v=>v],['photoSaturation','photoSaturationV',v=>v],['photoBlur','photoBlurV',v=>v],['photoOpacity','photoOpacityV',v=>v+'%'],['bgTolerance','bgToleranceV',v=>v]];pairs.forEach(([a,b,fmt])=>$(b).textContent=fmt($(a).value))}
function syncPhotoControls(){const st=ensurePhoto($('photoSelect').value);for(const [id,key] of [['photoZoom','zoom'],['photoRotate','rotate'],['photoX','x'],['photoY','y'],['photoBrightness','brightness'],['photoContrast','contrast'],['photoSaturation','saturation'],['photoBlur','blur'],['photoOpacity','opacity'],['bgTolerance','tolerance']])$(id).value=st[key];$('photoGray').checked=st.gray;$('photoSepia').checked=st.sepia;$('flipH').checked=st.flipH;$('flipV').checked=st.flipV;syncPhotoOutputs(st);drawPhotoEditor()}
function bindPhotoControls(){for(const [id,key] of [['photoZoom','zoom'],['photoRotate','rotate'],['photoX','x'],['photoY','y'],['photoBrightness','brightness'],['photoContrast','contrast'],['photoSaturation','saturation'],['photoBlur','blur'],['photoOpacity','opacity'],['bgTolerance','tolerance']])$(id).addEventListener('input',()=>{const st=ensurePhoto($('photoSelect').value);st[key]=+$(''+id).value;syncPhotoOutputs(st);drawPhotoEditor();render()});for(const [id,key] of [['photoGray','gray'],['photoSepia','sepia'],['flipH','flipH'],['flipV','flipV']])$(id).addEventListener('change',()=>{ensurePhoto($('photoSelect').value)[key]=$(id).checked;drawPhotoEditor();render()});$('photoSelect').addEventListener('change',syncPhotoControls)}
function drawPhotoEditor(){const key=$('photoSelect').value,im=imgCache[assets[key]?.src];pe.width=360;pe.height=220;pctx.clearRect(0,0,pe.width,pe.height);if(!im){pctx.fillStyle='#74899d';pctx.font='700 14px Inter';pctx.textAlign='center';pctx.fillText('Upload or choose a photo',180,110);return}const st=ensurePhoto(key),sc=Math.min(340/im.width,190/im.height);pctx.save();pctx.translate(180+st.x,110+st.y);pctx.rotate(st.rotate*Math.PI/180);pctx.scale((st.flipH?-1:1)*st.zoom/100,(st.flipV?-1:1)*st.zoom/100);pctx.globalAlpha=st.opacity/100;pctx.filter=`brightness(${st.brightness}%) contrast(${st.contrast}%) saturate(${st.saturation}%) blur(${st.blur}px)${st.gray?' grayscale(100%)':''}${st.sepia?' sepia(100%)':''}`;pctx.drawImage(im,-im.width*sc/2,-im.height*sc/2,im.width*sc,im.height*sc);pctx.restore();pctx.filter='none'}
async function quickRemoveBG(){const key=$('photoSelect').value,a=assets[key];if(!a?.src)return alert('Upload a photo first.');const im=await loadImg(a.src);if(!im)return;const c=document.createElement('canvas');c.width=im.naturalWidth||im.width;c.height=im.naturalHeight||im.height;const x=c.getContext('2d'),d=x.createImageData(c.width,c.height);x.drawImage(im,0,0);const data=x.getImageData(0,0,c.width,c.height),p=data.data,t=+$('bgTolerance').value||45,samples=[];for(const [sx,sy] of [[0,0],[c.width-1,0],[0,c.height-1],[c.width-1,c.height-1]]){const i=(sy*c.width+sx)*4;samples.push([p[i],p[i+1],p[i+2]])}const seen=new Uint8Array(c.width*c.height),q=[];const similar=(i,s)=>{const dr=p[i]-s[0],dg=p[i+1]-s[1],db=p[i+2]-s[2];return Math.sqrt(dr*dr+dg*dg+db*db)<=t};function visit(px,py){const n=py*c.width+px;if(seen[n])return;const idx=n*4;if(samples.some(s=>similar(idx,s))){seen[n]=1;p[idx+3]=0;q.push([px,py])}}for(const pt of [[0,0],[c.width-1,0],[0,c.height-1],[c.width-1,c.height-1]])visit(...pt);for(let h=0;h<q.length;h++){const [xx,yy]=q[h];for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=xx+dx,ny=yy+dy;if(nx>=0&&ny>=0&&nx<c.width&&ny<c.height)visit(nx,ny)}}x.putImageData(data,0,0);const url=c.toDataURL('image/png');assets[key].src=url;imgCache[url]=await loadImg(url);ensurePhoto(key).bgRemoved=true;drawPhotoEditor();render();status('Background removed • transparent PNG ready')}
function restorePhoto(){const key=$('photoSelect').value,a=assets[key];if(!a?.original)return;assets[key].src=a.original;ensurePhoto(key).bgRemoved=false;drawPhotoEditor();render();status('Original photo restored')}
async function exportPhotoPNG(){const key=$('photoSelect').value,a=assets[key];if(!a?.src)return alert('Upload a photo first.');const im=await loadImg(a.src);if(!im)return;const st=ensurePhoto(key),c=document.createElement('canvas');c.width=im.naturalWidth||im.width;c.height=im.naturalHeight||im.height;const x=c.getContext('2d');x.save();x.translate(c.width/2+st.x,c.height/2+st.y);x.rotate(st.rotate*Math.PI/180);x.scale((st.flipH?-1:1)*st.zoom/100,(st.flipV?-1:1)*st.zoom/100);x.globalAlpha=st.opacity/100;x.filter=`brightness(${st.brightness}%) contrast(${st.contrast}%) saturate(${st.saturation}%) blur(${st.blur}px)${st.gray?' grayscale(100%)':''}${st.sepia?' sepia(100%)':''}`;x.drawImage(im,-im.width/2,-im.height/2,im.width,im.height);x.restore();const aEl=document.createElement('a');aEl.download='edited-photo.png';aEl.href=c.toDataURL('image/png');aEl.click()}
function drawWatercolor(){ctx.save();ctx.globalAlpha=.12;ctx.fillStyle='#e6a74f';ctx.beginPath();ctx.ellipse(520,125,310,85,-.08,0,Math.PI*2);ctx.fill();ctx.fillStyle='#4e9a78';ctx.beginPath();ctx.ellipse(680,250,335,88,-.12,0,Math.PI*2);ctx.fill();ctx.restore()}
async function render(){const token=++renderToken;ctx.clearRect(0,0,W,H);ctx.fillStyle=val('pageBg')||'#fff';ctx.fillRect(0,0,W,H);drawWatercolor();ctx.strokeStyle=val('pageBorder')||'#1d507f';ctx.lineWidth=3;ctx.strokeRect(18,18,W-36,H-36);
const keys=['headerPhoto','leftLogo','rightLogo','leaderPhoto'];const ims=await Promise.all(keys.map(k=>loadImg(assets[k]?.src)));if(token!==renderToken)return;const [header,left,right,leader]=ims;
let z=p('headerPhoto');drawPhoto(header,268+z.x,25+z.y,550*(z.scale/100),385*(z.scale/100),'headerPhoto',false);z=p('leftLogo');drawPhoto(left,62+z.x,40+z.y,180*(z.scale/100),180*(z.scale/100),'leftLogo',false);z=p('rightLogo');drawPhoto(right,845+z.x,40+z.y,180*(z.scale/100),180*(z.scale/100),'rightLogo',false);
let q=p('quote');ctx.save();ctx.translate(q.x,q.y);ctx.rotate(q.rotate*Math.PI/180);drawText('“'+esc(val('quote'))+'”',772,205,270,25*q.scale/100,'600','left',val('quoteColor'),'Playfair Display',5);ctx.restore();let qa=p('quoteAuthor');ctx.save();ctx.translate(qa.x,qa.y);txt('– '+esc(val('quoteAuthor')),770,345,15,'800','left',val('textColor'));ctx.restore();
let t=p('title');ctx.save();ctx.translate(t.x,t.y);ctx.rotate(t.rotate*Math.PI/180);drawText(esc(val('mainTitle')),544,430,810,55*t.scale/100,'800','center',val('textColor'));ctx.restore();let st=p('subtitle');ctx.save();ctx.translate(st.x,st.y);ctx.rotate(st.rotate*Math.PI/180);drawText(esc(val('subtitle')),544,475,640,31*st.scale/100,'800','center',val('textColor'));ctx.restore();
let lc=p('leaderCard');ctx.save();ctx.translate(lc.x,lc.y);ctx.scale(lc.scale/100,lc.scale/100);ctx.rotate(lc.rotate*Math.PI/180);roundRect(195,510,697,190,+val('cardRadius')||12,val('leaderFill'),val('leaderBorder'),+val('borderWidth')||2);ctx.strokeStyle=val('accentColor');ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(425,540);ctx.lineTo(425,670);ctx.stroke();ctx.restore();
let lp=p('leaderPhoto');ctx.save();ctx.translate(lp.x,lp.y);ctx.rotate(lp.rotate*Math.PI/180);drawPhoto(leader,212,527,156*(lp.scale/100),156*(lp.scale/100),'leaderPhoto',true);ctx.restore();ctx.save();ctx.beginPath();ctx.arc(290+lp.x,605+lp.y,78*(lp.scale/100),0,Math.PI*2);ctx.strokeStyle=val('photoRing');ctx.lineWidth=+val('ringWidth');ctx.stroke();ctx.restore();if(!leader)fillPhotoPlaceholder(212+lp.x,527+lp.y,156*(lp.scale/100),156*(lp.scale/100),'LEADER PHOTO',true);
[['leaderName','leaderName',450,550,31,'800'],['leaderMobile','leaderMobile',450,590,18,'700'],['leaderSemester','leaderSemester',450,622,18,'700'],['leaderSubject','leaderSubject',450,654,18,'700']].forEach(([id,key,x,y,size,wt])=>{const pp=p(key);ctx.save();ctx.translate(pp.x,pp.y);ctx.rotate(pp.rotate*Math.PI/180);drawText(esc(val(id)),x,y,430,size*pp.scale/100,wt,'left',val('textColor'),'Inter',2);ctx.restore()});
let gh=p('groupHeader');ctx.save();ctx.translate(gh.x,gh.y);ctx.rotate(gh.rotate*Math.PI/180);ctx.scale(gh.scale/100,gh.scale/100);ctx.strokeStyle=val('lineColor');ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(55,755);ctx.lineTo(330,755);ctx.moveTo(757,755);ctx.lineTo(1032,755);ctx.stroke();roundRect(345,726,397,62,31,val('accentColor'),val('accentColor'),2);drawText('GROUP MEMBERS',544,757,380,29,'800','center','#fff','Inter',1);ctx.restore();
const n=+$('memberCount').value,rows=rowPlan(n),ma=p('membersArea');const gap=+$('memberGap').value||14;let y=812+ma.y;const areaH=550, rowGap=30, rowH=Math.max(122,(areaH-rowGap*(rows.length-1))/rows.length);let idx=1;for(const count of rows){const cardW=(W-80-gap*(count-1))/count,startX=(W-(count*cardW+gap*(count-1)))/2+ma.x;for(let c=0;c<count;c++){await drawMember(idx,startX+c*(cardW+gap),y,cardW,rowH);idx++}y+=rowH+rowGap}
let f=p('footer');ctx.save();ctx.translate(f.x,f.y);ctx.rotate(f.rotate*Math.PI/180);ctx.scale(f.scale/100,f.scale/100);ctx.fillStyle=val('footerColor');ctx.beginPath();ctx.moveTo(0,1437);ctx.quadraticCurveTo(300,1490,560,1450);ctx.quadraticCurveTo(800,1410,1087,1470);ctx.lineTo(1087,1536);ctx.lineTo(0,1536);ctx.closePath();ctx.fill();ctx.strokeStyle=val('footerColor');ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(0,1417);ctx.quadraticCurveTo(300,1477,560,1438);ctx.quadraticCurveTo(800,1400,1087,1458);ctx.stroke();drawText('✦   '+esc(val('footer'))+'   ✦',544,1442,650,22,'800','center',val('textColor'),'Inter',1);ctx.restore();
}
async function drawMember(i,x,y,w,h){const m=makeMember(i);const card=makePos('memberCard'+i),photo=makePos('memberPhoto'+i),name=makePos('memberName'+i),det=makePos('memberDetails'+i);const bx=x+m.x+card.x,by=y+m.y+card.y;roundRect(bx,by,w*card.scale/100,h*card.scale/100,+val('cardRadius'),val('cardFill'),val('cardBorder'),+val('borderWidth'));const r=Math.min(w*.23,57),pcx=bx+w/2+photo.x,pcy=by+r+2+photo.y;ctx.save();ctx.rotate(photo.rotate*Math.PI/180);const im=await loadImg(assets['member'+i]?.src);if(im)drawPhoto(im,pcx-r, pcy-r,2*r*photo.scale/100,2*r*photo.scale/100,'member'+i,true);else fillPhotoPlaceholder(pcx-r,pcy-r,2*r,2*r,'PHOTO',true);ctx.restore();ctx.beginPath();ctx.arc(pcx,pcy,r+6,0,Math.PI*2);ctx.strokeStyle=val('photoRing');ctx.lineWidth=+val('ringWidth');ctx.stroke();const d=memberData(i);ctx.save();ctx.translate(name.x,name.y);ctx.rotate(name.rotate*Math.PI/180);drawText(d.name.toUpperCase(),bx+w/2,by+r*2+48,w-16,fitFont(d.name.toUpperCase(),w-16,17,8,'800')*name.scale/100,'800','center',val('textColor'),'Inter',1);ctx.restore();ctx.save();ctx.translate(det.x,det.y);ctx.rotate(det.rotate*Math.PI/180);const ds=Math.max(7,Math.min(13,fitFont('MOBILE NO : '+d.mobile,w-14,13,7,'700')))*det.scale/100;drawText('MOBILE NO : '+d.mobile,bx+w/2,by+r*2+78,w-14,ds,'700','center',val('textColor'),'Inter',1);drawText('SEMESTER : '+d.semester,bx+w/2,by+r*2+98,w-14,ds,'700','center',val('textColor'),'Inter',1);drawText('SUBJECT : '+d.subject,bx+w/2,by+r*2+118,w-14,ds,'700','center',val('textColor'),'Inter',2);ctx.restore()}
let dragging=false,lastPt=null;poster.addEventListener('pointerdown',e=>{dragging=true;lastPt={x:e.clientX,y:e.clientY};poster.setPointerCapture(e.pointerId)});poster.addEventListener('pointermove',e=>{if(!dragging)return;const r=poster.getBoundingClientRect(),sx=W/r.width,sy=H/r.height,st=getPos($('elementSelect').value);st.x=clamp(st.x+(e.clientX-lastPt.x)*sx,-550,550);st.y=clamp(st.y+(e.clientY-lastPt.y)*sy,-700,700);lastPt={x:e.clientX,y:e.clientY};syncLayoutControls();render()});['pointerup','pointercancel'].forEach(ev=>poster.addEventListener(ev,()=>dragging=false));
function allFields(){const o={};document.querySelectorAll('input,textarea,select').forEach(e=>{if(e.type!=='file'&&e.id)o[e.id]=e.value});return o}
function saveDraft(silent=false){const members={};for(let i=1;i<=+$('memberCount').value;i++)members[i]=makeMember(i);const payload={fields:allFields(),assets,positions,photoState,memberState:members,version:4};localStorage.setItem('nssPosterDraftProV4',JSON.stringify(payload));status('Draft saved');if(!silent)alert('Draft saved on this device.')}
function loadDraft(){const raw=localStorage.getItem('nssPosterDraftProV4');if(!raw)return alert('No saved draft found.');const d=JSON.parse(raw);Object.entries(d.fields||{}).forEach(([id,v])=>{if($(id))$(id).value=v});Object.assign(assets,d.assets||{});Object.assign(positions,d.positions||{});Object.assign(photoState,d.photoState||{});Object.keys(memberState).forEach(k=>delete memberState[k]);Object.assign(memberState,d.memberState||{});initMembers();syncLayoutControls();syncPhotoControls();syncDesignOutputs();render();status('Draft loaded')}
function resetAll(){if(confirm('Reset the poster and start again?')){localStorage.removeItem('nssPosterDraftProV4');location.reload()}}
function status(t){$('statusText').textContent=t}
async function exportCanvas(){await render();const scale=+$('quality').value||2,c=document.createElement('canvas');c.width=W*scale;c.height=H*scale;c.getContext('2d').drawImage(poster,0,0,c.width,c.height);return c}
async function downloadPoster(type){const c=await exportCanvas(),a=document.createElement('a'),nm='NSS-'+(esc(val('groupName'))||'Poster').replace(/\s+/g,'-');a.download=nm+'.'+type;a.href=c.toDataURL(type==='jpg'?'image/jpeg':'image/png',.96);a.click();status(type.toUpperCase()+' exported')}
async function downloadPDF(){const c=await exportCanvas(),J=window.jspdf?.jsPDF;if(!J)return alert('PDF library failed to load. Connect to internet and retry.');const pdf=new J({orientation:'portrait',unit:'mm',format:'a4'});pdf.addImage(c.toDataURL('image/jpeg',.96),'JPEG',0,0,210,297);pdf.save('NSS-'+(esc(val('groupName'))||'Poster').replace(/\s+/g,'-')+'.pdf');status('PDF exported')}
function resetPreviewZoom(){const wrap=$('previewWrap');const avail=Math.min(wrap.clientWidth-24,wrap.clientHeight-24);const scale=clamp(Math.min(avail/W,1),.25,1);previewScale=scale;applyPreviewZoom()}
let previewScale=.72;function applyPreviewZoom(){$('poster').style.width=(W*previewScale)+'px';$('poster').style.height=(H*previewScale)+'px';$('previewZoom').textContent=Math.round(previewScale*100)+'%'}
$('zoomIn').onclick=()=>{previewScale=clamp(previewScale+.05,.25,1);applyPreviewZoom()};$('zoomOut').onclick=()=>{previewScale=clamp(previewScale-.05,.25,1);applyPreviewZoom()};$('fitPreview').onclick=()=>resetPreviewZoom();
function setupTabs(){$('tabs').querySelectorAll('button').forEach(btn=>btn.onclick=()=>{$('tabs').querySelectorAll('button').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));btn.classList.add('active');$('tab-'+btn.dataset.tab).classList.add('active')})}
$('openEditorBtn').onclick=()=>{$('editorPanel').classList.add('open')};$('mobileEdit').onclick=()=>{$('editorPanel').classList.add('open')};$('closeEditorBtn').onclick=()=>{$('editorPanel').classList.remove('open')};
async function boot(){for(let i=1;i<=10;i++)makeMember(i);const ms=$('memberCount');for(let i=1;i<=10;i++){const o=document.createElement('option');o.value=i;o.textContent=i+' member'+(i>1?'s':'');ms.appendChild(o)}ms.value=8;Object.entries(defaults).forEach(([k,v])=>{$(k).value=v});setupTabs();bindGeneral();bindPhotoControls();$('headerPhotoFile').addEventListener('change',e=>readFile(e,'headerPhoto'));$('leftLogoFile').addEventListener('change',e=>readFile(e,'leftLogo'));$('rightLogoFile').addEventListener('change',e=>readFile(e,'rightLogo'));$('leaderPhotoFile').addEventListener('change',e=>readFile(e,'leaderPhoto'));initMembers();syncDesignOutputs();syncLayoutControls();syncPhotoControls();await Promise.all(['headerPhoto','leftLogo','rightLogo'].map(k=>loadImg(assets[k].src)));render();resetPreviewZoom();setInterval(()=>saveDraft(true),15000)}
boot();
