const $=id=>document.getElementById(id);const state={members:[],leaderPhoto:'',heroPhoto:'',logoLeft:'',logoRight:'',bgPhoto:''};
const defaults={groupName:'APJ ABDUL KALAM',mainTitle:'NSS GROUP LEADER',quote:'Dream is not what you see in sleep,\nDream is something that does not let you sleep.',quoteAuthor:'APJ ABDUL KALAM',footerText:'NOT ME BUT YOU',leaderName:'YOUR NAME',leaderMobile:'9876543210',leaderSemester:'5TH SEM',leaderSubject:'GEOGRAPHY HONOURS',memberCount:8,accent:'#123f78',cardColor:'#effaff',wash:65,borderWidth:2,cardRadius:10,font:'Arial',theme:'blue',quality:2};
function toast(m){const t=$('toast');t.textContent=m;t.classList.add('show');clearTimeout(window._toast);window._toast=setTimeout(()=>t.classList.remove('show'),1800)}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function readImage(file,cb){if(!file)return;const r=new FileReader();r.onload=()=>cb(r.result);r.readAsDataURL(file)}
function makeMember(i){return{name:`MEMBER ${i}`,mobile:`987654${String(320+i).slice(-4)}`,semester:'5TH SEM',subject:'YOUR SUBJECT',photo:'',zoom:1,x:0,y:0}}
function ensureMembers(n){while(state.members.length<n)state.members.push(makeMember(state.members.length+1));state.members.length=n;renderForms();renderMembers();saveLocal()}
function renderForms(){const box=$('memberForms');box.innerHTML='';state.members.forEach((m,i)=>{const w=document.createElement('div');w.className='member-form';w.innerHTML=`<h3>Member ${i+1}</h3><label>Name<input data-k="name" data-i="${i}" value="${esc(m.name)}"></label><div class="grid2"><label>Mobile<input data-k="mobile" data-i="${i}" value="${esc(m.mobile)}"></label><label>Semester<input data-k="semester" data-i="${i}" value="${esc(m.semester)}"></label></div><label>Subject<input data-k="subject" data-i="${i}" value="${esc(m.subject)}"></label><label>Photo<input data-photo="${i}" type="file" accept="image/*"></label><div class="range-grid"><label>Zoom<input data-zoom="${i}" type="range" min=".6" max="2.4" step=".01" value="${m.zoom}"></label><label>X<input data-x="${i}" type="range" min="-100" max="100" value="${m.x}"></label><label>Y<input data-y="${i}" type="range" min="-100" max="100" value="${m.y}"></label></div><div class="mini-actions"><button data-clear="${i}">Clear photo</button><button data-dup="${i}">Duplicate</button></div>`;box.appendChild(w)});
box.querySelectorAll('[data-k]').forEach(e=>e.oninput=()=>{state.members[+e.dataset.i][e.dataset.k]=e.value;renderMembers();saveLocal()});box.querySelectorAll('[data-photo]').forEach(e=>e.onchange=()=>readImage(e.files[0],src=>{state.members[+e.dataset.photo].photo=src;renderMembers();saveLocal()}));['zoom','x','y'].forEach(k=>box.querySelectorAll(`[data-${k}]`).forEach(e=>e.oninput=()=>{state.members[+e.dataset[k]][k]=+e.value;renderMembers();saveLocal()}));box.querySelectorAll('[data-clear]').forEach(e=>e.onclick=()=>{state.members[+e.dataset.clear].photo='';renderForms();renderMembers();saveLocal()});box.querySelectorAll('[data-dup]').forEach(e=>e.onclick=()=>{if(state.members.length>=10)return toast('Maximum 10 members');state.members.splice(+e.dataset.dup+1,0,JSON.parse(JSON.stringify(state.members[+e.dataset.dup])));$('memberCount').value=state.members.length;renderForms();renderMembers();saveLocal()})}
function columns(n){if(n<=2)return 2;if(n<=6)return 3;return 4}
function renderMembers(){const g=$('membersGrid');const n=state.members.length;g.style.gridTemplateColumns=`repeat(${columns(n)},1fr)`;g.style.gridAutoRows=n<=2?'1fr':n<=4?'1fr':n<=6?'1fr':'1fr';g.innerHTML='';state.members.forEach(m=>{const c=document.createElement('div');c.className='member-card';c.innerHTML=`<div class="member-photo"><img><div class="member-placeholder">PHOTO</div></div><div class="member-name">${esc(m.name)}</div><div class="member-detail"><b>MOBILE</b><span>:</span><span>${esc(m.mobile)}</span></div><div class="member-detail"><b>SEMESTER</b><span>:</span><span>${esc(m.semester)}</span></div><div class="member-detail"><b>SUBJECT</b><span>:</span><span>${esc(m.subject)}</span></div>`;const im=c.querySelector('img'),ph=c.querySelector('.member-placeholder');if(m.photo){im.src=m.photo;im.style.display='block';ph.style.display='none';im.style.objectPosition=`calc(50% + ${m.x/4}px) calc(50% + ${m.y/4}px)`;im.style.transform=`scale(${m.zoom})`}g.appendChild(c)})}
function bindText(id,view,fn=v=>esc(v)){const f=()=>{$(view).innerHTML=fn($(id).value);saveLocal()};$(id).addEventListener('input',f);f()}
bindText('groupName','groupView');bindText('mainTitle','titleView');bindText('quote','quoteView',v=>esc(v).replace(/\n/g,'<br>'));bindText('quoteAuthor','quoteAuthorView');bindText('footerText','footerView');bindText('leaderName','leaderNameView');bindText('leaderMobile','leaderMobileView');bindText('leaderSemester','leaderSemesterView');bindText('leaderSubject','leaderSubjectView');
$('memberCount').onchange=e=>ensureMembers(+e.target.value);['accent','cardColor','borderWidth','cardRadius','font'].forEach(id=>$(id).oninput=applyDesign);$('wash').oninput=applyDesign;$('quality').onchange=updateSize;
function applyDesign(){document.documentElement.style.setProperty('--accent',$('accent').value);document.documentElement.style.setProperty('--card',$('cardColor').value);document.documentElement.style.setProperty('--border',$('borderWidth').value+'px');document.documentElement.style.setProperty('--radius',$('cardRadius').value+'px');document.documentElement.style.setProperty('--font',$('font').value);document.querySelectorAll('.wash').forEach(x=>x.style.opacity=(+$('wash').value/100)*.55);applyTheme();saveLocal()}
function applyTheme(){const t=$('theme').value;const c={blue:'#123f78',green:'#236b4b',maroon:'#7a2535',black:'#222'}[t]||'#123f78';$('accent').value=c;document.documentElement.style.setProperty('--accent',c)}$('theme').onchange=()=>{applyTheme();applyDesign()};
$('leaderPhoto').onchange=e=>readImage(e.target.files[0],src=>{state.leaderPhoto=src;showLeader();saveLocal()});['leaderZoom','leaderX','leaderY'].forEach(id=>$(id).oninput=showLeader);function showLeader(){const im=$('leaderImg'),ph=document.querySelector('.portrait-placeholder');if(state.leaderPhoto){im.src=state.leaderPhoto;im.style.display='block';ph.style.display='none';im.style.transform=`translate(${$('leaderX').value/5}px,${$('leaderY').value/5}px) scale(${$('leaderZoom').value})`}else{im.style.display='none';ph.style.display='flex'}}
$('heroPhoto').onchange=e=>readImage(e.target.files[0],src=>{state.heroPhoto=src;showHero();saveLocal()});$('showHero').onchange=showHero;function showHero(){const im=$('heroImg'),ph=$('.hero-placeholder');if(state.heroPhoto&&$('showHero').checked){im.src=state.heroPhoto;im.style.display='block';ph.style.display='none'}else{im.style.display='none';ph.style.display='flex'}}
[['logoLeft','logoLeftImg','logo-left-ph'],['logoRight','logoRightImg','logo-right-ph'],['bgPhoto','poster-bg','']].forEach(([input,target,ph])=>$(input).onchange=e=>readImage(e.target.files[0],src=>{state[input]=src;if(target==='poster-bg'){$('.poster-bg').style.backgroundImage=`url(${src})`;$('poster').querySelector('.poster-bg').style.opacity='.22'}else{$(target).src=src;$(target).style.display='block';if(ph)$('.'+ph).style.display='none'};saveLocal()}));
function updateSize(){const q=+$('quality').value;$('sizeLabel').textContent=`${Math.round(794*q)} × ${Math.round(1123*q)} px @ ${q}×`}
async function capture(type){if(typeof html2canvas==='undefined')return toast('Export library did not load. Refresh and try again.');const q=+$('quality').value;const canvas=await html2canvas($('poster'),{scale:q,backgroundColor:'#fff',useCORS:true,logging:false});const a=document.createElement('a');a.download=`NSS-Poster-${Date.now()}.${type==='jpeg'?'jpg':'png'}`;a.href=canvas.toDataURL(type==='jpeg'?'image/jpeg':'image/png',.96);a.click();toast('Download ready')}
$('downloadPng').onclick=()=>capture('png');$('downloadJpg').onclick=()=>capture('jpeg');$('downloadPdf').onclick=async()=>{if(typeof html2canvas==='undefined')return toast('Refresh and try again');const q=+$('quality').value;const c=await html2canvas($('poster'),{scale:q,backgroundColor:'#fff'});const {jsPDF}=window.jspdf;const p=new jsPDF({orientation:'portrait',unit:'mm',format:'a4'});p.addImage(c.toDataURL('image/jpeg',.96),'JPEG',0,0,210,297,undefined,'FAST');p.save(`NSS-Poster-${Date.now()}.pdf`);toast('PDF ready')};
function data(){const fields={};['groupName','mainTitle','quote','quoteAuthor','footerText','leaderName','leaderMobile','leaderSemester','leaderSubject','memberCount','accent','cardColor','wash','borderWidth','cardRadius','font','theme','quality'].forEach(k=>fields[k]=$(k).value);return{version:2,fields,members:state.members,leaderPhoto:state.leaderPhoto,heroPhoto:state.heroPhoto,logoLeft:state.logoLeft,logoRight:state.logoRight,bgPhoto:state.bgPhoto,showHero:$('showHero').checked}}
function saveLocal(){try{localStorage.setItem('nssPosterPro',JSON.stringify(data()))}catch(e){}}
function loadData(p){Object.entries(p.fields||{}).forEach(([k,v])=>{if($(k))$(k).value=v});state.members=p.members||[];state.leaderPhoto=p.leaderPhoto||'';state.heroPhoto=p.heroPhoto||'';state.logoLeft=p.logoLeft||'';state.logoRight=p.logoRight||'';state.bgPhoto=p.bgPhoto||'';$('showHero').checked=p.showHero!==false;ensureMembers(+$('memberCount').value);applyDesign();renderForms();renderMembers();showLeader();showHero();if(state.logoLeft){$('logoLeftImg').src=state.logoLeft;$('logoLeftImg').style.display='block';$('.logo-left-ph').style.display='none'}if(state.logoRight){$('logoRightImg').src=state.logoRight;$('logoRightImg').style.display='block';$('.logo-right-ph').style.display='none'}if(state.bgPhoto){$('.poster-bg').style.backgroundImage=`url(${state.bgPhoto})`;$('.poster-bg').style.opacity='.22'}updateSize()}
$('saveProject').onclick=()=>{const a=document.createElement('a');a.download='NSS-Poster-Studio-Pro.json';a.href=URL.createObjectURL(new Blob([JSON.stringify(data())],{type:'application/json'}));a.click();toast('Project saved')};$('loadProject').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{loadData(JSON.parse(r.result));saveLocal();toast('Project loaded')}catch(err){toast('Invalid project file')}};r.readAsText(f)};
$('resetProject').onclick=()=>{if(confirm('Reset poster to default?')){loadData({fields:defaults,members:[],showHero:true});state.members=[];ensureMembers(defaults.memberCount);toast('Reset complete')}};
$('fillDemo').onclick=()=>{state.members.forEach((m,i)=>{m.name=['RINA SARKER','SREEJAINI MUKHERJEE','BARSHA GHOSH','SAHAJAN GAZI','SAIFUDDIN GAZI','MRINMOY DAS','CHAYAN DAS','MEMBER 8','MEMBER 9','MEMBER 10'][i]||`MEMBER ${i+1}`;m.semester='5TH SEM';m.subject=i===0?'GEOGRAPHY HONOURS':i===3?'EDUCATION HONOURS':'GENERAL';m.mobile=`9${String(800000000+i).slice(0,9)}`});renderForms();renderMembers();saveLocal();toast('Demo data filled')};$('clearPhotos').onclick=()=>{state.leaderPhoto='';state.heroPhoto='';state.logoLeft='';state.logoRight='';state.bgPhoto='';state.members.forEach(m=>m.photo='');renderForms();renderMembers();showLeader();showHero();$('logoLeftImg').style.display='none';$('logoRightImg').style.display='none';$('.logo-left-ph').style.display='flex';$('.logo-right-ph').style.display='flex';$('.poster-bg').style.opacity='0';saveLocal();toast('Photos cleared')};
(function init(){let p=null;try{p=JSON.parse(localStorage.getItem('nssPosterPro')||'null')}catch(e){}if(p)loadData(p);else{Object.entries(defaults).forEach(([k,v])=>{if($(k))$(k).value=v});ensureMembers(defaults.memberCount);applyDesign();updateSize();showLeader();showHero()}})();
